language: java
matrix:
  include:
    - os: linux
      sudo: false
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode9.1
      env: JAVA_HOME=$(/usr/libexec/java_home)
script: ./build.sh -Dexist.autodeploy=off -Dtest.haltonerror=true -Dtest.haltonfailure=true travis
notifications:
  hipchat: ec8fcfa661addc56a361a8ef536320@integrations
